### ISSUE TITLE
Disable yellowbox warning

### ISSUE THREAD

**Issue by ruskid** [reactotron/reactotron#100]
Is there any config option to disable the warnings?

**Comment by skellock** [comment]
Not currently.  I'll put one in.  Thanks for the heads up

**Comment by skellock** [comment]
So, I'm on the fence about yellowboxes now entirely.

I've just changed the whole code base and intentionally left out yellow box forwarding.  Turns out, its useful, but it's WAY too chatty.

I'll 100% welcome a plugin to forward these off, but it sounds like I'm on the same page as you... get rid of them!  =)
