### ISSUE TITLE
reactotron-redux - Github link

### ISSUE THREAD

**Issue by GantMan** [reactotron/reactotron#132]
https://www.npmjs.com/package/reactotron-redux

Clicking the github link on the right side results in a 404, probably since you moved packages out?

Would love to see the source of `reactotron-redux` not sure where it is anymore.  Filing issue here out of shear stupidity.

**Comment by skellock** [comment]
Sorry @GantMan .  I think this is caused because I'm living off the `next` branch and not `master`.

I'll swap over next week.

Here's the components you're seeing.

https://github.com/reactotron/reactotron/tree/next/packages

If you're doing PRs', make sure you're targeting `next`.   Until `next` week!  :)

Sorry.
