### ISSUE TITLE
Support Windows and Linux

### ISSUE THREAD

**Issue by skellock** [reactotron/reactotron#195]
Starting to get some folks asking for it.

**Comment by rmevans9** [comment]
I just tested building this on a windows machine and had 0 issues. I have yet to test if a React app can connect to it (a project for tomorrow probably...) but is there a specific issue that you know of that prevents this from working on Windows?

**Comment by skellock** [comment]
Wow, really?  I fired up my Windows box last weekend and had a lot of problems with dependencies.  I never quite figured them all out in the end.

There are some build scripts I use to link dependencies together in various repos.  Those are shell scripts at the moment.  I'd like to upgrade those to JS files using ShellJS.

Are you using the new linux shell extension on Windows?

**Comment by rmevans9** [comment]
I guess I slightly misrepresented - During npm install I did run into an error about node-gyp but I just tried to build anyway since all the other packages seemed to have installed and it built without issue and ran. I am currently trying to build it on a different windows box and hope I have the same success.

I was not using the new linux shell extension, just plain ol commandline and npm. 

Assuming the build that is going on right now works I will actually be testing it with a ReactJS application on a windows box this morning. I will be reporting any success/failure.

Note that currently I am only trying to get the electron app to run, I have not looked at the CLI based tool that you have.

**Comment by rmevans9** [comment]
After messing with it for a while since the site I am testing is served up over https I set the Reactotron client to use secure but the app wouldn't allow the connection. I then took off secure and Chrome complained about insecure content with secure content - once I allowed that.... IT CONNECTED! Going to setup the redux plugin now and see if I can't get at my state.

**Comment by skellock** [comment]
The CLI works fine.

I got passed the node-gyp issues (missing CL.exe) by installing the visual c++ runtime from Visual Studio 2015 and adding more things to the path.

I got to the point where there was no build errors, but just got a empty app once launching.

I feel like we're close!

I really appreciate you jumping in here.  I switched to the Mac in 2006, so I'm not very familiar with dev tools any longer.  :)

**Comment by rmevans9** [comment]
I wonder why you are seeing an empty app? I have never seen an empty app even with ignoring the node-gyp issues and just building.

**Comment by skellock** [comment]
I'm not sure.  I'll have another look today.

Try setting `secure: true` in your configure line when you setup Reactotron.  This will use `wss` instead of `ws`.

**Comment by rmevans9** [comment]
yeah, I did that but it refused to connect to the socket io server running in the app over wss for some reason. I have to move back on to some work so I just gave up the battle for now since I found the work around of not connecting over the secure websocket channel. 

On a side note - Redux actions are being reported! Woo!

**Comment by rmevans9** [comment]
also... once this is up and running a few items I have noted that will need to be updated:

- Key Binding pictures are very mac specific.
- Dispatch an action keybinding needs to change (the command button on windows is the windows key. Windows Key + D == show desktop...)

**Comment by rmevans9** [comment]
Not sure if this is a windows thing or maybe even an issue within the app I am testing with... but in some situations my web app gets "stuck" when I have Reactotron connected up. I have found that it has to do with the redux store enhancer being in. I am going to dig into this more later to see where the issue lies and if it is a windows issue or a global issue.

**Comment by rmevans9** [comment]
Disregard my last issue - this is not specific to windows I would image. In our app it looks like an action is dispatched with a payload of a react component and that sent the Reactotron React Store Enhancer into a spinning cycle when it tried to send the action over socket io to the app. This likely needs a fix but is not related to this ticket. I will investigate and possibly open a PR to resolve if I find a good solution.

**Comment by skellock** [comment]
Thanks for all this exploring!  I'll get those keybinding over to control for windows.

**Comment by rmevans9** [comment]
Not a problem - I have loved using Reactotron on my React Native apps and really want to get this going at my day job which uses windows machines. I really want to see this happen for Windows.

Also a quick fix for my unrelated issue was to use the except option to ignore that action type.

**Comment by skellock** [comment]
![hellowindows](https://cloud.githubusercontent.com/assets/68273/18313908/d69653ae-74de-11e6-8c22-548dc3ba8417.png)

My problems were related to build-time issues.  If I just installed the reactotron dependencies from npm, all is well.

So a few issues I can straighten out, but ya... we should be good to go with Windows!

Thanks again.

**Comment by rmevans9** [comment]
@skellock sorry for the delay in my response. I am very pleased to hear that!

**Comment by waqas19921** [comment]
When building in windows it reports error in downloading electron as the parsing line
`DEFAULT_OPTS.version = stdout.split('electron-prebuilt@')[1].replace(/\s/g, '')`
not returns the exact electron version only so the link generated will be inaccessible and the build stops.

**Comment by skellock** [comment]
@waqas19921 I noticed this yesterday too.  I think there's something up with the electron packager trying to download the 1.4.0 electron runtime.  I hardcoded it to use 1.3.2 in the package.json `package` script for now.  I'll try again tomorrow to see what's up.

**Comment by skellock** [comment]
@waqas19921 https://github.com/reactotron/reactotron/pull/210 should fix the packager issue.

**Comment by waqas19921** [comment]
Hope this will fix the problem.

**Comment by waqas19921** [comment]
@skellock can you release gui package for windows now.

**Comment by skellock** [comment]
I've yet to crack the mystery of proper binary signing on Windows.  I should have more time this week.  I can put up one without signing though, just not sure how much people will (or should) trust me.

**Comment by skellock** [comment]
Turns out we don't need to sign windows & linux builds.  I'll include all 3 platforms going forward, but leave Windows & Linux in "beta" stage until I get proper shiny installers.

**Comment by THPubs** [comment]
Guys can you please tell me how to compile and run this on Linux?

**Comment by rmevans9** [comment]
I believe that you can just call the package command in the reactotron-app folder:

`npm run package` (you could probably use yarn as well.

**Comment by skellock** [comment]
There are [pre-built binaries](https://github.com/reactotron/reactotron/releases/tag/v1.5.0) you can use if you're just looking to use it.

Sounds like you're trying to hack on it though.

I'd recommend `git clone` then `npm i` to install the root level deps like `lerna`.  Then run `yarn run welcome` to bootstrap your environment.

It's been a challenge to get everything running in a dev environment from scratch.  I'm hoping to make that easier when I get some spare cycles.

Just holler here if you have any problems along the way.

**Comment by THPubs** [comment]
@rmevans9 @skellock Ah cool thanks. Sorry I did not see the pre built binaries :smile:

**Comment by fkrauthan** [comment]
Since this app now has official windows builds too you might wanna change the README to mark that. Right now when visiting the repository it seems its a Mac only app.

**Comment by skellock** [comment]
I've been holding off until I get the icons in place and some feedback from people. But I can add a comment pointing folks at the binaries.  Thx.
