### ISSUE TITLE
Clarity on tips on running in production

### ISSUE THREAD

**Issue by varungupta85** [reactotron/reactotron#215]
This is not an issue in the package but a question regarding one of the tips for running in production. [Here](https://github.com/reactotron/reactotron/blob/master/docs/tips.md#running-in-production) it says that we shouldn't running Reactotron in production by wrapping Reactotron activities within `__DEV__` and then it follows to say `This means you'll need to be careful to use require() instead of import as import in ES6 are hoisted!`. I guess this is more of an ES6 question but I am not sure if I understand what would happen if `import` is used instead of `require`. Does that mean that since the `import` statements are hoisted, even if I import `Reactotron` within the `__DEV__` block, it will be hoisted and if the dependency is installed as `--save-dev`, it would throw an error?

**Comment by skellock** [comment]
Correct.

You'll have to use a require instead of an import.

Check out this example:

`https://github.com/reactotron/reactotron/blob/master/packages/demo-react-js/src/ReactotronConfig.js`

The other option is to use `--save` and just do an `if` statement around your `connect` in your `ReactotronConfig.js`.

The extra files really aren't a big deal for React Native.   You just want to make sure you're not trying to use it in production (by production I mean the app store).
