### ISSUE TITLE
Support for fetch

### ISSUE THREAD

**Issue by lindskogen** [reactotron/reactotron#26]
Logging `fetch` requests

**Comment by skellock** [comment]
We'll have to do `fetch` logging manually.  It doesn't support:

* a pipeline you hook to passively monitor all requests
* a timer
* the ability to always `resolve` the promise instead of `reject`ing it.

Up till now, `apisauce` had preferential treatment because it was trivial to implement, and has no impact at all at the call sites of each request.

What we should do though, is provide a consistent way for api libraries to talk to that `apibox` on the right.

Thanks!

**Comment by skellock** [comment]
Coming soon, but we now have an interface which you can write your own plugin for the API communication.

Here's the interface:
https://github.com/reactotron/reactotron/tree/next/packages/reactotron-core-client#apiresponse

Here's an example of what it might look like:
https://github.com/reactotron/reactotron/blob/next/packages/reactotron-apisauce/src/index.js

**Comment by JeandeCampredon** [comment]
Hi @skellock,

Sounds like an amazing idea, I would love to be able to give a shot at writing a plugin but the links above are dead.
Any updates ? 

thanks ;)

**Comment by skellock** [comment]
Updated.  They were pointing to the `next` branch which was pre-release.  Now they are pointing to `master`.

Let me know if you have any questions or see any problems.

**Comment by JeandeCampredon** [comment]
ok thanks ;)
