### ISSUE TITLE
Unable to resolve module react-native/Libraries/Core/Devtools/parseErrorStack from .../node_modules/reactotron-react-native/dist/index.js

### ISSUE THREAD

**Issue by flaz83** [reactotron/reactotron#312]
Good morning.
After cloning my repository on other computer, I have this error on simulator and device.

Unable to resolve module react-native/Libraries/Core/Devtools/parseErrorStack from .../node_modules/reactotron-react-native/dist/index.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/react-native/Libraries/Core/Devtools/parseErrorStack and its parent directories

I figured out that the folder required in reactotron-react-native/dist/index.js doesn't exist 'react-native/Libraries/Core/Devtools/parseErrorStack'.
If I change 

parseErrorStack = parseErrorStack || require('react-native/Libraries/Core/Devtools/parseErrorStack')
symbolicateStackTrace = symbolicateStackTrace || require('react-native/Libraries/Core/Devtools/symbolicateStackTrace')

to

parseErrorStack = parseErrorStack || require('react-native/Libraries/JavaScriptAppEngine/Initialization/parseErrorStack');
       symbolicateStackTrace = symbolicateStackTrace || require('react-native/Libraries/JavaScriptAppEngine/Initialization/symbolicateStackTrace');

My app works again.
Any suggestion? Thanks a lot

**Comment by rmevans9** [comment]
What version of react-native are you running?

**Comment by flaz83** [comment]
react-native 0.34.1

**Comment by skellock** [comment]
Look like perhaps in 35 they moved files around.  These are all internal facing files for React Native, so, stuff like this is going to happen.

One thing we could do is what @flaz83 is suggesting, is have fallbacks.  I kinda wish there was an external facing version number for React Native we could check to do stuff like this.  There was talks a while ago about putting something on `window.navigator`, but I haven't checked in a few months to see if that came through.

Sorry for the stress.  Great work in deciphering that.

Is upgrading your RN an option?  I ask because if it's not an option (which NO is totally a fine answer!!!), then I'll look into making the change you suggest.

**Comment by Cadiac** [comment]
+1 to this issue, running react-native 0.35.0. I cloned my repository on another computer and started getting this error today.

**Comment by skellock** [comment]
Looks like they moved the files around in version 0.37.  Bummer.

I have the require inside a try/catch already, but `require` seems to be one of those things that can bring the house down if it's missing.

Still looking at a few options here to support older versions.

**Comment by lavarene** [comment]
I'm using react-native 0.35.0 and ran into the same issue. @flaz83 Your fix worked. Thank you!

**Comment by kumarpatel** [comment]
flaz83 I'm confused by your suggested fix.
I don't see the line you're suggesting to change in `reactotron-react-native/dist/index.js`
Do you have your fix in a fork that I could point against?

**Comment by flaz83** [comment]
reactotron/blob/master/packages/reactotron-react-native/src/plugins/track-global-errors.js
line 74

**Comment by kumarpatel** [comment]
Got it. Thanks @flaz83 
Fix works me as well.

**Comment by kumarpatel** [comment]
Another question: How do I rebuild the `reactotron-react-native/dist` dir after making the change in `reactotron-react-native/src/plugins/track-global-errors.js`?

**Comment by rmevans9** [comment]
@kumarpatel '''yarn (or npm) run build''' <- assumes node_modules are installed

**Comment by bbubn** [comment]
Hi,
One more with same error on RN 0.35.0

**Comment by laurelli-indyres** [comment]
Same as above. RN 0.35.0, and the fix proposed by @flaz83 does resolve the issue for me as well.

**Comment by devinceble** [comment]
Any news?

**Comment by skellock** [comment]
Ok.  Sorry for the grief folks.

This is caused because facebook change the location of its' internal files in 0.37.0.  It's kinda our fault for using them... but damn it, i want nice things!

So... here's our outs:

1.  Upgrade to React Native 0.37.0 🎉 

In the meantime, if you can't or wont (which i totally understand!!!) I just made a new package called `reactotron-react-native-under-37`.  Uninstall your old one and install this one.

When you import or require, use:

```js
import Reactotron from 'reactotron-react-native-under-37'
```

I don't plan on keeping this around forever, but hopefully this will make your codebases behave again.

Feel free to log any issues you find with this.  I've moved my projects up to RN 40 now, so I won't be actively testing this.

**Comment by juddey** [comment]
Thanks man! Just hit this. Running React Native 33. 

This might just be the push I need to write some more tests so I can upgrade react native versions to the latest and greatest, with at least some sort of safety net.

**Comment by li-zhenyu** [comment]
@skellock 
met this issue,
React Native 0.42.0
