### ISSUE TITLE
Alt support

### ISSUE THREAD

**Issue by avishayil** [reactotron/reactotron#61]
Hi,
Is there any chance for alt flux support?
https://github.com/goatslacker/alt

Create store using alt:
```javascript
export default alt.createStore(TodoStore, 'TodoStore');
```

**Comment by skellock** [comment]
I've got a rebuild on the go which makes Reactotron state agnostic.  Instead of pushing up redux-specific info, I push `json`.  It's a really subtle difference but it will allow us to use different stores such as Redux, Mobx, and apparently `alt flux` which I'm just learning about as I type this.

We will have to write a small plugin to support this, however.

Lemme click around on their site and see what's up.

Thx!

**Comment by avishayil** [comment]
Thanks for the quick response! really looking for it!

**Comment by skellock** [comment]
1.0 will be driven by a JSON interface, so it'll be possible to write your own plugin to support Alt.  I'll be shipping redux (already done) and mobx stores as examples.

You can see the interface here:

https://github.com/reactotron/reactotron/tree/next/packages/reactotron-core-client#messages

Look for the `state.*` messages.  Hopefully they make sense in the context of alt.

**Comment by DanlanNZ** [comment]
@avishayil did you ever get this working with Alt?
